from fastapi import APIRouter, Depends, HTTPException, Response
from sqlalchemy.orm import Session, joinedload
from database import get_db
from auth_utils import get_current_user
import models
import schemas
from datetime import datetime
import io

router = APIRouter(prefix="/api/reports", tags=["reports"])


def _generate_text_report(assessment: models.Assessment, org: models.Organization) -> str:
    lines = []
    lines.append("=" * 60)
    lines.append("RISK ASSESSMENT REPORT")
    lines.append("=" * 60)
    lines.append(f"Organization : {org.name}")
    lines.append(f"Industry     : {org.industry or 'N/A'}")
    lines.append(f"Assessment   : {assessment.title}")
    lines.append(f"Date         : {datetime.utcnow().strftime('%Y-%m-%d')}")
    lines.append(f"Overall Score: {assessment.overall_score:.1f} / 10")
    lines.append("")

    if assessment.ai_analysis:
        lines.append("EXECUTIVE SUMMARY")
        lines.append("-" * 40)
        lines.append(assessment.ai_analysis)
        lines.append("")

    lines.append("RISK REGISTER")
    lines.append("-" * 40)

    categories = {}
    for risk in assessment.risks:
        cat = risk.category or "other"
        categories.setdefault(cat, []).append(risk)

    for cat, risks in categories.items():
        lines.append(f"\n[{cat.upper()}]")
        for risk in risks:
            lines.append(f"  • {risk.name}")
            lines.append(f"    Probability: {risk.probability} | Impact: {risk.impact} | Score: {risk.score:.1f}")
            lines.append(f"    Status: {risk.status}")
            if risk.description:
                lines.append(f"    {risk.description}")
            if risk.mitigations:
                lines.append("    Mitigations:")
                for m in risk.mitigations:
                    lines.append(f"      - {m.title}")

    lines.append("")
    lines.append("=" * 60)
    lines.append("Generated by RiskIQ Platform")
    return "\n".join(lines)


def _generate_pdf_report(assessment: models.Assessment, org: models.Organization) -> bytes:
    try:
        from reportlab.lib.pagesizes import A4
        from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
        from reportlab.lib.colors import HexColor, white, black
        from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle
        from reportlab.lib.units import cm
        from reportlab.lib.enums import TA_CENTER, TA_LEFT

        buffer = io.BytesIO()
        doc = SimpleDocTemplate(buffer, pagesize=A4, topMargin=2*cm, bottomMargin=2*cm)
        styles = getSampleStyleSheet()

        brand_blue = HexColor('#2563EB')
        dark_bg = HexColor('#1E293B')
        light_gray = HexColor('#F8FAFC')
        danger_red = HexColor('#EF4444')
        warn_amber = HexColor('#F59E0B')
        ok_green = HexColor('#10B981')

        title_style = ParagraphStyle('Title', parent=styles['Title'],
            fontSize=24, textColor=brand_blue, spaceAfter=6)
        h2_style = ParagraphStyle('H2', parent=styles['Heading2'],
            fontSize=14, textColor=dark_bg, spaceBefore=12, spaceAfter=6)
        body_style = ParagraphStyle('Body', parent=styles['Normal'],
            fontSize=10, spaceAfter=4)

        story = []

        # Header
        story.append(Paragraph("RISK ASSESSMENT REPORT", title_style))
        story.append(Paragraph(f"<b>{org.name}</b> — {assessment.title}", styles['Heading3']))
        story.append(Paragraph(f"Generated: {datetime.utcnow().strftime('%B %d, %Y')}", body_style))
        story.append(Spacer(1, 0.5*cm))

        # Score table
        score_color = danger_red if assessment.overall_score >= 7 else warn_amber if assessment.overall_score >= 4 else ok_green
        score_data = [
            ['Overall Risk Score', 'Status', 'Industry', 'Risks Identified'],
            [
                f"{assessment.overall_score:.1f} / 10",
                assessment.status.title(),
                assessment.industry or 'N/A',
                str(len(assessment.risks)),
            ]
        ]
        score_table = Table(score_data, colWidths=[4*cm, 3*cm, 5*cm, 4*cm])
        score_table.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (-1, 0), dark_bg),
            ('TEXTCOLOR', (0, 0), (-1, 0), white),
            ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
            ('FONTSIZE', (0, 0), (-1, -1), 10),
            ('GRID', (0, 0), (-1, -1), 0.5, HexColor('#CBD5E1')),
            ('BACKGROUND', (0, 1), (0, 1), score_color),
            ('TEXTCOLOR', (0, 1), (0, 1), white),
            ('FONTNAME', (0, 1), (0, 1), 'Helvetica-Bold'),
            ('FONTSIZE', (0, 1), (0, 1), 14),
            ('ALIGN', (0, 0), (-1, -1), 'CENTER'),
            ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
            ('ROWBACKGROUNDS', (0, 1), (-1, 1), [light_gray]),
            ('TOPPADDING', (0, 0), (-1, -1), 8),
            ('BOTTOMPADDING', (0, 0), (-1, -1), 8),
        ]))
        story.append(score_table)
        story.append(Spacer(1, 0.5*cm))

        if assessment.ai_analysis:
            story.append(Paragraph("Executive Summary", h2_style))
            story.append(Paragraph(assessment.ai_analysis, body_style))
            story.append(Spacer(1, 0.3*cm))

        # Risk Register
        story.append(Paragraph("Risk Register", h2_style))
        risk_data = [['Risk', 'Category', 'Probability', 'Impact', 'Score', 'Status']]
        for risk in sorted(assessment.risks, key=lambda r: r.score or 0, reverse=True):
            sev = (risk.severity or 'low').lower()
            row_color = danger_red if sev == 'critical' else warn_amber if sev == 'high' else ok_green
            risk_data.append([
                risk.name[:40],
                (risk.category or '').title(),
                (risk.probability or '').title(),
                (risk.impact or '').title(),
                f"{risk.score:.1f}",
                (risk.status or '').title(),
            ])

        risk_table = Table(risk_data, colWidths=[5.5*cm, 3*cm, 2.5*cm, 2.5*cm, 1.5*cm, 2.5*cm])
        risk_table.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (-1, 0), dark_bg),
            ('TEXTCOLOR', (0, 0), (-1, 0), white),
            ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
            ('FONTSIZE', (0, 0), (-1, -1), 9),
            ('GRID', (0, 0), (-1, -1), 0.5, HexColor('#CBD5E1')),
            ('ALIGN', (0, 0), (-1, -1), 'CENTER'),
            ('ALIGN', (0, 1), (0, -1), 'LEFT'),
            ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
            ('ROWBACKGROUNDS', (0, 1), (-1, -1), [white, light_gray]),
            ('TOPPADDING', (0, 0), (-1, -1), 6),
            ('BOTTOMPADDING', (0, 0), (-1, -1), 6),
        ]))
        story.append(risk_table)

        story.append(Spacer(1, 1*cm))
        story.append(Paragraph("Generated by RiskIQ Platform | Confidential", body_style))

        doc.build(story)
        buffer.seek(0)
        return buffer.read()

    except Exception as e:
        text = _generate_text_report(assessment, org)
        return text.encode("utf-8")


@router.post("")
def create_report(
    data: schemas.ReportCreate,
    db: Session = Depends(get_db),
    current_user: models.User = Depends(get_current_user),
):
    assessment = (
        db.query(models.Assessment)
        .options(
            joinedload(models.Assessment.risks).joinedload(models.Risk.mitigations)
        )
        .filter(
            models.Assessment.id == data.assessment_id,
            models.Assessment.organization_id == current_user.organization_id,
        )
        .first()
    )
    if not assessment:
        raise HTTPException(status_code=404, detail="Assessment not found")

    org = db.query(models.Organization).filter(
        models.Organization.id == current_user.organization_id
    ).first()

    report = models.Report(
        title=data.title or f"{assessment.title} — Risk Report",
        report_type=data.report_type,
        status="completed",
        assessment_id=assessment.id,
        created_by_id=current_user.id,
    )
    db.add(report)
    db.commit()
    db.refresh(report)
    return report


@router.get("")
def list_reports(
    db: Session = Depends(get_db),
    current_user: models.User = Depends(get_current_user),
):
    reports = (
        db.query(models.Report)
        .join(models.Assessment)
        .filter(models.Assessment.organization_id == current_user.organization_id)
        .order_by(models.Report.created_at.desc())
        .all()
    )
    return reports


@router.get("/{report_id}/download")
def download_report(
    report_id: int,
    format: str = "pdf",
    db: Session = Depends(get_db),
    current_user: models.User = Depends(get_current_user),
):
    report = (
        db.query(models.Report)
        .join(models.Assessment)
        .filter(
            models.Report.id == report_id,
            models.Assessment.organization_id == current_user.organization_id,
        )
        .first()
    )
    if not report:
        raise HTTPException(status_code=404, detail="Report not found")

    assessment = (
        db.query(models.Assessment)
        .options(
            joinedload(models.Assessment.risks).joinedload(models.Risk.mitigations)
        )
        .filter(models.Assessment.id == report.assessment_id)
        .first()
    )
    org = db.query(models.Organization).filter(
        models.Organization.id == current_user.organization_id
    ).first()

    if format == "pdf":
        content = _generate_pdf_report(assessment, org)
        return Response(
            content=content,
            media_type="application/pdf",
            headers={"Content-Disposition": f'attachment; filename="risk_report_{report_id}.pdf"'},
        )
    else:
        text = _generate_text_report(assessment, org)
        return Response(
            content=text,
            media_type="text/plain",
            headers={"Content-Disposition": f'attachment; filename="risk_report_{report_id}.txt"'},
        )
